title: "PECS"
description: Workshop on Performance and Energy efficiency in Concurrent and Distributed Systems

# Change this to the year which shall appear as "default" in the website
current_year: 2025

# The following array is used to populate previous editions.
# If the edition is hosted by this site, a corresponding _edition_20xx
# folder is expected to be found, and `output: true` should be set.
# Otherwise, `site` should point to the previous webpage (if available).
# `proceedings` should point to the digital library page of the proceedings (if availbale).
# `venue`, `location`, and `dates` allow to customize the edition website. The current
# markdown files rely on them throughout the text, so if you clone the content of a past
# edition and set these variables correctly, a good part of the site is already consistent.
collections:
  '2025':
    description: Workshop on Performance and Energy Efficiency in Concurrent and Distributed Systems  
    output: true
    permalink: /:collection/:title
    venue: "Department of Computer Science (Polo Fibonacci), University of Pisa, Largo Bruno Pontecorvo 3"            
    location: "Dresden, Germany"
    dates: "August 25-26, 2025 "
    max_pagelimit: "12"
    min_pagelimit: "10"    
    short_pagelimit: "0"
    submission_link: "TBA"
    additionalinfo: "Co-located with Euro-Par 2025"  
  '2024':
    description: Workshop on Performance and Energy Efficiency in Concurrent and Distributed Systems  
    output: true
    permalink: /:collection/:title
    venue: "Department of Computer Science (Polo Fibonacci), University of Pisa, Largo Bruno Pontecorvo 3"            
    location: "Pisa, Italy"
    dates: "June 3, 2024"
    max_pagelimit: "12"
    min_pagelimit: "10"    
    short_pagelimit: "0"
    submission_link: "https://pecs2024.hotcrp.com/paper/new"
    additionalinfo: "Co-located with HPDC 2024"
  '2023':
    description: Workshop on Performance and Energy Efficiency in Concurrent and Distributed Systems  
    output: true
    permalink: /:collection/:title
    venue: "St. Raphael Resort"
    location: "Limassol, Cyprus"
    dates: "August 28, 2023"
    max_pagelimit: "12"
    min_pagelimit: "10"    
    short_pagelimit: "0"
    submission_link: "https://easychair.org/my/conference?conf=europar2023workshops"
    additionalinfo: "Co-located with Euro-PAR 2023"
  '2022':
    description: Workshop on Performance and Energy Efficiency in Concurrent Systems
    output: true
    permalink: /:collection/:title
    venue: "Virtual Event"
    location: "virtual conference"
    dates: "April 9, 2022"
    pagelimit: "8"
    short_pagelimit: "4"
    submission_link: "https://easychair.org/my/conference?conf=pecs2022"
  '2021':
    description: Workshop on Performance and Energy Efficiency in Concurrent Systems
    output: true
    permalink: /:collection/:title
    venue: "INRIA Conference center"
    location: "Rennes, France"
    dates: "April 20, 2021"
    pagelimit: "8"
    short_pagelimit: "4"
    submission_link: "https://easychair.org/my/conference?conf=pecs2021"


# You are not likely expected to touch below this line
exclude: [README.md, LICENSE]

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: true

sass:
  style: compressed
